### ISSUE TITLE
dialogs.php пропал

### ISSUE THREAD

**Issue by junkym0nk3y** [Chiaki/VKBK#10]
Где брать?

**Comment by Chiaki** [comment]
Действительно. По факту пропажи была проведена проверка, а dialogs.php объявлен в федеральный розыск. План "Перехват" дал результат и скрипт возвращен в репозиторий.

**Comment by junkym0nk3y** [comment]
Notice: Uninitialized string offset: 0 in /var/www/vk/dialogs.php on line 75
Warning: Illegal string offset 'path' in /var/www/vk/dialogs.php on line 80

Всё-равно болеет. Пользуясь случаем (ну что бы новый тикет не открывать), есть ещё бага, что больше 200 сообщений со стены не синхронизирует. Что в "полной синхронизации", что в быстрой.

В остальном всё очень круто, большое спасибо.

**Comment by Chiaki** [comment]
Спасибо за выявление ошибок. Большая просьба давать ещё описание при котором они произошли (получились) хотя бы краткое. А в максимуме ещё и описание окружения в котором скрипт работает (версия PHP например). Это поможет понять что не так и как это поправить.

По нотису и варнингу пока могу предположить что отсутствуют данные для построения списка.
Но локально воспроизвести пока не удалось.

Касательно синхронизации стены постараюсь глянуть. Возможно изменения в API. По логу синхронизации какая картина? Увеличивается ли счетчик, либо постоянно запрашивается один и тот же диапазон и т.д.

**Comment by junkym0nk3y** [comment]
Debian 8
PHP: 7.0.31-1 dotdeb+8.1
SQL: 10.1.35-MariaDB-1 jessie

По поводу синхронизации стены пишет:
> Получаем записи 1 - 100 / 1928 со стены ВК.
> Перехожу к следующей порции сообщений...

А по окончанию:
> Получаем записи 100 - 200 / 1928 со стены ВК.
> Великая китайская! Быстрая синхронизация сообщений завершена.

Останавливается с url'ом sync-wall.php?offset=100&fast=
В итоге так и остаётся 200 сообщений.
UPD. прописал вручную offset=200&fast=false, получил ещё 100 сообщений со стены, теперь 300.

А по поводу диалогов, может чуть больше прояснит более полный лог. Вылезает он в списке чатов и повторяется каждый раз:
```
Warning: Illegal string offset 'first_name' in /var/www/vk/dialogs.php on line 75
Notice: Uninitialized string offset: 0 in /var/www/vk/dialogs.php on line 75
Warning: Illegal string offset 'last_name' in /var/www/vk/dialogs.php on line 75
Notice: Uninitialized string offset: 0 in /var/www/vk/dialogs.php on line 75
Warning: Illegal string offset 'path' in /var/www/vk/dialogs.php on line 80
Notice: Uninitialized string offset: 0 in /var/www/vk/dialogs.php on line 80
Warning: Illegal string offset 'photo_path' in /var/www/vk/dialogs.php on line 80
Notice: Uninitialized string offset: 0 in /var/www/vk/dialogs.php on line 80
```

Если зайти в сам диалог, то
`Notice: Undefined offset: 5347431 in /var/www/vk/ajax/dialog-paginator.php on line 142`

**Comment by Chiaki** [comment]
Касательно синхронизации стены: скорее всего там аналогичный баг недавно закрытому при синхронизации фото. Хотя пустой fast должен приводить к полной синхронизации каждый раз а не к остановке.

В диалогах какой порядок действий у вас был? После синхронизации диалогов скачивали фото для профилей в очереди закачки?
Стоит глянуть в базе `vk_profiles` какие данные сохранились для ID 5347431

**Comment by Chiaki** [comment]
Ошибку с `Warning: Illegal string offset 'first_name' in /var/www/vk/dialogs.php on line 75` получилось воспроизвести. 
Причина: отсутствие необходимой информации в таблице пользователей\групп (судя по id, пользователей).
Решение: добавлена проверка и в случае ошибки выводится блок "Неопознанный пользователь".
Почему информация не сохранилась или сохранилась неправильно мне пока не понятно.

По синхронизации стены, обновите файлы `index.php` и `sync-wall.php` . Сохраняется ли некорректное поведение при синхронизации?

**Comment by junkym0nk3y** [comment]
Ок, я понял в чём причина была, похоже. Я про диалоги.

Я в начале неправильно конфиг настроил, думал в путях сохранения нужно указать абсолютный адрес директории. Потом всё поменял и обнулил таблицы с изображениями, чтобы они появились. 

Видимо нужно профили тоже дропнуть и заново синхронизацию запустить. Можно как-то отдельно синхронизацию профилей друзей и прочего запустить? Или надо logout делать и заново синхронизировать всё?

**Comment by junkym0nk3y** [comment]
Со стеной теперь всё хорошо. Спасибо.

**Comment by Chiaki** [comment]
С путями может быть путаница, да.

Отдельной синхронизации профилей увы нет. Данная информация подтягивается как побочная при синхронизации стены и диалогов. Но думаю если обнулить таблицу профилей и групп, а потом запустить синхронизацию диалогов то всё необходимое подтянется. Если сами диалоги уже синхронизированы, то переходить ко второй части (синхронизации сообщений) не понадобится.

Logout делать не обязательно. Он вообще на случай проблем с токеном чтобы не лезть в базу. (:
По-умолчанию запрашивается offline токен который не имеет срока годности.
