### ISSUE TITLE
Вечная загрузка диалога

### ISSUE THREAD

**Issue by ecub** [Chiaki/VKBK#12]
Вечная загрузка: 
<img width="778" alt="2018-09-07 2 07 12" src="https://user-images.githubusercontent.com/9007645/45189881-c1df7400-b243-11e8-8df4-e8e96d21ceb1.png">

Сопровождается ошибкой:
<img width="791" alt="2018-09-07 2 11 44" src="https://user-images.githubusercontent.com/9007645/45189884-c60b9180-b243-11e8-956a-48a9bb62e5b3.png">

К сожалению, обновление до 0.8.3 не помогло пофиксить проблему.

VKBK Version: 0.8.3
PHP Version: 7.1.16
Mac OS, Safari (в Firefox тоже самое)

**Comment by Chiaki** [comment]
Спасибо что подробно всё описали.
Судя по описанию, в процессе обработки происходит ошибка в PHP в результате чего на выход отдаётся не чистый json. Можете глянуть нет ли чего "лишнего" в том что отдаёт скрипт?
Для этого необходимо запустить синхронизацию с открытым Developer tools и когда выскочит ошибка посмотреть Response для последнего запроса к `sync-message.php` на вкладке Network.

**Comment by ecub** [comment]
Сорри, я немного пьян и не хочу отправить чего-то лишнего сейчас случайно, но там действительно ошибка: 

```
<font style="color:red;font-weight:bold;">Плохой запрос: INSERT INTO `vk_messages_attach`
 (`uid`,`wall_id`,`type`,`is_local`,`attach_id`,`owner_id`,`uri`,`path`,`width`,`height`,`text`,`date`,`access_key`,`title`,`duration`,`player`,`link_url`,`caption`,`skipthis`) VALUES
Incorrect string value: '\xF0\x9F\x91\x89 v...' for column 'text' at row 1</font>
```

Между строк что-то про vk.com/video_ext.php. Докину завтра, если будет необходимо.

**Comment by Chiaki** [comment]
Спасибо. Этой информации пока достаточно.
Когда будет время, создайте бэкап базы и выполните следующие запросы:
```
ALTER TABLE `vk_messages_attach` CHANGE `text` `text` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE `vk_messages_attach` CHANGE `title` `title` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;
```
Это должно решить проблему.

**Comment by ecub** [comment]
Это решило проблему! <3

**Comment by ecub** [comment]
Похожую ошибку поймал:

```
<font style="color:red;font-weight:bold;">Плохой запрос: INSERT INTO `vk_messages_attach`
	    (`uid`,`wall_id`,`type`,`is_local`,`attach_id`,`owner_id`,`uri`,`path`,`width`,`height`,`text`,`date`,`access_key`,`title`,`duration`,`player`,`link_url`,`caption`,`skipthis`)
	    VALUES
	    (NULL,2243165,'link',0,1491250758,0,'','',0,0,'',1491250758,'','404 Not Found',0,'','https://youtu.be/KHsEQmWSRTs\','',0)
	    ON DUPLICATE KEY UPDATE
	    `wall_id` = 2243165, `type` = 'link', `is_local` = 0, `attach_id` = 1491250758, `owner_id` = 0, `uri` = '', `width` = 0, `height` = 0, `text` = '', `date` = 1491250758, `access_key` = '', `title` = '404 Not Found', `duration` = 0, `player` = '', `link_url` = 'https://youtu.be/KHsEQmWSRTs\', `caption` = '', `skipthis` = 0
	    
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'link', `is_local` = 0, `attach_id` = 1491250758, `owner_id` = 0, `uri` = '', `wi' at line 4</font>
```

**Comment by Chiaki** [comment]
Хм, это уже интересней. Это весь текст ошибки?

**Comment by ecub** [comment]
@Chiaki поправил текст, теперь весь.

**Comment by Chiaki** [comment]
Спасибо, сейчас понятна причина. Обновите у себя файл `classes/func.php` из репозитория.
P.S. После успешной синхронизации я попрошу вас дёрнуть из базы данный урл, интересно откуда там взялся обратный слэш.

**Comment by ecub** [comment]
В бд слеша нет, в VK это выглядит как ссылка, видос и еще одна ссылка из-за того, что ролик доступен только авторизованным пользователям. И еще это все внутри конференции:

<img width="390" alt="2018-09-08 13 40 53" src="https://user-images.githubusercontent.com/9007645/45253270-382bc580-b36d-11e8-8d98-dd82f2dda000.png">

Алсо, наверное не стоит создавать отдельный issue для этого, но у меня не отображаются картинки и стикеры в диалогах, и аватарки пользователей. Путь до них почему-то выглядит как: http://host/data/profiles, http://host/data/stickers, и т. д. Это макось, возможно я неправильно указал пути, как это должно выглядеть? Я рассчитывал на такое: /users/admin/documents/dump/photo, но это не работает, похоже. Создадутся ли они прямо в хосте, если на него путь укажу?

**Comment by Chiaki** [comment]
А после `...WSRTs` в поле `link_url` для записи с типом `link` больше ничего? С данной ссылкой у вас должно быть две записи, одна для типа video и одна для link. Просто предполагаю что слэш мог быть следствием экранированной части url, но если ничего нет то видимо ВК её потом выкинул. (:

> Алсо, наверное не стоит создавать отдельный issue для этого, но у меня не отображаются картинки и стикеры в диалогах, и аватарки пользователей.

Вы их скачивали к себе локально через очередь закачки? Аватарки пользователей, групп и стикеры и должны иметь такой путь. Директория `data` и поддиректории создались в корне скрипта?

**Comment by ecub** [comment]
Да, точно. В link_url слеш есть. Ну т.е это и выглядит как: https://youtu.be/KHsEQmWSRTs\

Для типа video же вообще link_url пуст, но это кажется для любых видеозаписей так.

Не-а, но если попробовать что-то оттуда скачать, то получаю ошибку:  Невозможно получить данные с удаленного хоста, либо Warning: mkdir(): Permission denied in /Library/WebServer/Documents/classes/curl.php on line 79 и ошибка при сохранении файла.

А вот data не создалась вообще, да. Я так понимаю это права доступа нужно поправить?

**Comment by Chiaki** [comment]
Понятно. Теперь буду знать что ВК не особо фильтрует данные. Либо ошиблись вставляя линк и получился такой вот казус.)

Да, с правами доступа проблема. PHP не может создать там директорию, поэтому и ошибка.
