### ISSUE TITLE
Синхронизация диалогов не сохраняет профили собеседников в БД

### ISSUE THREAD

**Issue by fearmear** [Chiaki/VKBK#13]
### Expected behavior \ Ожидаемое поведение
После синхронизация сообщений отображаются диалоги с именами собеседников. Диалог можно прочесть нажав на имя.

### Actual behavior \ Текущее поведение
После синхронизация сообщений отображаются диалоги с "Неопознанный пользователь" вместо имен собеседников. По клику на "Неопознанный пользователь" ничего не происходит.
При этом в таблице vk_profiles пусто.

### Steps to reproduce the behavior \ Шаги для воспроизведения
1. Пустая БД из vkbk.sql
2. Авторизируемся
3. Запускаем синхронизацию диалогов
4. Открываем список диалогов по завершению синхронизации
5. Видим список диалогов с "Неопознанный пользователь" вместо имен собеседников.

Что интересно: после синхронизации стены некоторые диалоги стали работать как ожидалось.

- - - -
### Additional information
VKBK Version:
0.8.1 beta
PHP Version:
5.3.13
OS:
Windows 10

- - - -
Other Comments:

**Comment by fearmear** [comment]
Создал [Pull Request](https://github.com/Chiaki/VKBK/pull/14/) с возможным фиксом

**Comment by Chiaki** [comment]
Здравствуйте. 
**Причина:** сохранение информации пользователей и групп было отключено для дебага и не включено обратно.
Исправлено. Обновите файл `ajax/sync-message.php` из репозитория.
