### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by MediaKirov** [Chiaki/VKBK#19]
https://github.com/Chiaki/VKBK/blob/nightly/classes/profiles.php в 56 строчке надо $this->vk->api

и следует при запуске скрипта выполнять проверки на установленные пакеты (ну и подсказывать что не так), в противном случае пришлось в логе смотреть в чем ошибки. Курл мб стр и прочее.

**Comment by Chiaki** [comment]
Касательно расширений подумаю что можно сделать. Как минимум, стоит добавить в документацию к системным требованиям. Хотя в большинстве случаев данные библиотеки включаются по-умолчанию при настройке веб-сервера. Но возможно в пакетных инсталляторах что-то поменялось за это время.
