### ISSUE TITLE
Ошибка с очередью закачки, но при этом со второго-третьего раза картинка закачивается

### ISSUE THREAD

**Issue by BodyDub** [Chiaki/VKBK#20]
Записал видео по этому поводу. Думаю она лучше опишет проблему https://mega.nz/#!WNVFQAAS!x2lv-uTBgrREQmVG7ZQMP3ZIFou1bl21C6sE19ji35M

### Steps to reproduce the behavior \ Шаги для воспроизведения

- - - -
### Additional information
VKBK Version:

PHP Version:

OS:

- - - -
Other Comments:

**Comment by Chiaki** [comment]
~~Не то чтобы я параною, но не могли бы вы загрузить видео на сервис с возможностью онлайн-просмотра (например youtube). Заранее спасибо.~~

Обратите внимание на ID в адресной строке. ID с ошибкой заканчивается на 318. В автоматическом режиме идет поиск записи с сортировкой по дате добавления (т.е. данный ID не виден в списке). Поэтому когда вы сохраняете другие элементы, всё в порядке (сервер их отдает), а в автоматическом режиме опять запрашивается ID с 318 который недоступен.

Вы можете исключить его из очереди, тогда будет выбран другой ID.

**Comment by BodyDub** [comment]
https://mega.nz/#!HFNAGKZJ!fd-JqEAPa9ntYsvwOkfvu-bnBddaI-vLFLezxYUNzqQ

**Comment by BodyDub** [comment]
При загрузке документов нет возможности удалить файлы из очереди, соответсвенно, никак в автоматический режим не попасть
https://mega.nz/#!fNUCQAza!jPlE5J1Up5f6dHrfanFRtc0rqBlXDWBBL4OyEImK-Vw

**Comment by BodyDub** [comment]
ошибка при синхронизации видеозаписей
http://imageshack.com/a/img922/1552/AuvVf9.jpg
php 7.2

**Comment by Chiaki** [comment]
Да, к сожалению исключения из очереди документов пока нет. Но раз ВК такой "заботливый" что удаляет уже и документы... добавлю в ближайшее обновление.

p.s.
А по прямой ссылке (столбец URL) что отдает? Страницу с ошибкой либо что-то иное?

p.s.s.
По возможности обновитесь на nightly 0.8.7b.

**Comment by Chiaki** [comment]
> ошибка при синхронизации видеозаписей

Исправление данной ошибки добавлено в nightly.
