### ISSUE TITLE
messages API отключен для standalone-приложений

### ISSUE THREAD

**Issue by Chiaki** [Chiaki/VKBK#21]
### Expected behavior \ Ожидаемое поведение
Синхронизация диалогов

### Actual behavior \ Текущее поведение
Access denied: no access to call this method

### Steps to reproduce the behavior \ Шаги для воспроизведения
Попытка синхронизации диалогов

- - - -
### Additional information
VKBK Version: any

PHP Version: any

OS: any

- - - -
Other Comments:
Как обойти данную "фичу" пока не понятно. ):

**Comment by Vorobyshek** [comment]
Можно обойти это ограничение путем "прямой" авторизации по логину и паролю.

**Comment by Chiaki** [comment]
@Vorobyshek можно, но и обрабатывать придется не ответы api, а "грязный" html который может меняться хоть 10 раз в день. Есть надежда (и слухи) что возможно будет read-only api. Пока ждем-с.

**Comment by Vorobyshek** [comment]
@Chiaki, я могу предоставить готовый код для получения нормального токена и с нормальной отправкой api запросов.

**Comment by Chiaki** [comment]
@Vorobyshek если код под лицензией MIT, давайте. В ином случае надо уточнить под какой он лицензией, так как от этого зависит смогу ли я использовать его в скрипте.

А что вы подразумеваете под нормальным токеном? На данный момент, vkbk работает с токеном standalone-приложения, так как у этого типа приложений до конца февраля 2019 года была возможность работать с методом messages. Сейчас такая возможность есть только при вызове с ключом доступа сообщества либо через тестовый доступ для standalone-приложения который выдает администрация.

**Comment by Vorobyshek** [comment]
@Chiaki , есть ли возможность списаться не на GitHub ?
https://vk.com/jdussss
https://t.me/vor0byshek

**Comment by Vorobyshek** [comment]
@Chiaki, тут можно получить token для работы и с аудио и с сообщениями (нужно будет только внести небольшие изменения в код; метод работает **только** с авторизацией по логину и паролю)  
https://github.com/vodka2/vk-audio-token

**Comment by Chiaki** [comment]
@Vorobyshek спасибо за код, довольно интересно. Но будет ли такой метод авторизации работать с ID и ключом приложения пользователя, либо только если выдавать себя за один из официальных клиентов? Попробую оттестировать, но думаю что без маскировки оно работать не будет.

**Comment by Vorobyshek** [comment]
@Chiaki увы, работать будет только с "маскировкой", работает с оф. приложением и приложением для Iphone (на счет Kate уже не знаю)

**Comment by Chiaki** [comment]
Вариант решения через /dev применен в v0.8.12, надеюсь не сломают в очередной раз.
На данный момент это пожалуй самый оптимальный вариант в сравнении с альтернативами.
