### ISSUE TITLE
Ошибка при вызове mkdir из curl.php (line 76)

### ISSUE THREAD

**Issue by phatal** [Chiaki/VKBK#8]
### Expected behavior \ Ожидаемое поведение
В случае отсутствия необходимой директории для сохранения, та должна быть создана
### Actual behavior \ Текущее поведение
Директории не создается - выкидывается ошибка.
- - - -
### Additional information
VKBK Version:
0.7.6beta
PHP Version:
5.6.35
OS:
Win10 x64
 - - -
Other Comments:
Проблема решается путем добавления аргумента для рекурсивного создания директорий в вызов функции. Тем самым вызов из:
`mkdir($opts['path']);`
превращается в:
`mkdir($opts['path'], null, true)`
Второй аргумент отвечает за права доступа выставляемые на создаваемой директории/файле.

**Comment by Chiaki** [comment]
Спасибо. Исправлено в 0.7.7
