### ISSUE TITLE
Привет! висит на "Структура базы данных устарела. Обратитесь к инструкции по обновлению перед синхронизацией.  BK", в чем может быть проблема?

### ISSUE THREAD

**Issue by VetalRacer** [Chiaki/VKBK#9]
### Steps to reproduce the behavior \ Шаги для воспроизведения

- - - -
### Additional information
VKBK Version:

PHP Version:

OS:

- - - -
Other Comments:

**Comment by Chiaki** [comment]
Добрый день.
Данное сообщение отображается когда вы обновляете VKBK и новая версия содержит изменения в структуре базы данных. Перейдите по ссылке в сообщении и выполните необходимые запросы в БД (например через phpmyadmin) начиная с вашей предыдущей версии до той которую вы установили.

**Comment by VetalRacer** [comment]
Database changed
MariaDB [vk_local]> ALTER TABLE `vk_counters` ADD `dialogs` MEDIUMINT( 8 ) UNSIGNED NOT NULL;
ERROR 1060 (42S21): Duplicate column name 'dialogs'
MariaDB [vk_local]> ALTER TABLE `vk_counters` ADD `dialogs` MEDIUMINT( 8 ) UNSIGNED NOT NULL;
ERROR 1060 (42S21): Duplicate column name 'dialogs'
MariaDB [vk_local]> ALTER TABLE `vk_counters` ADD `dialogs` MEDIUMINT( 8 ) UNSIGNED NOT NULL;
ERROR 1060 (42S21): Duplicate column name 'dialogs'
MariaDB [vk_local]> 
MariaDB [vk_local]> ALTER TABLE `vk_counters` DROP INDEX `counters` ,
    -> ADD UNIQUE `counters` ( `album` , `photo` , `music` , `video` , `wall` , `docs` , `dialogs` );
Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

MariaDB [vk_local]> 
MariaDB [vk_local]> CREATE TABLE IF NOT EXISTS `vk_dialogs` (
    ->   `id` int(11) NOT NULL,
    ->   `date` int(11) NOT NULL,
    ->   `title` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    ->   `in_read` int(11) NOT NULL,
    ->   `multichat` tinyint(1) NOT NULL,
    ->   `chat_id` int(11) NOT NULL,
    ->   `admin_id` int(11) NOT NULL,
    ->   `users` int(11) NOT NULL,
    ->   `is_new` tinyint(1) NOT NULL,
    ->   `is_upd` tinyint(1) NOT NULL,
    ->   UNIQUE KEY `uchat` (`id`,`multichat`,`chat_id`,`admin_id`),
    ->   KEY `multi` (`multichat`),
    ->   KEY `admin` (`admin_id`),
    ->   KEY `uid` (`id`),
    ->   KEY `new` (`is_new`),
    ->   KEY `upd` (`is_upd`)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Query OK, 0 rows affected, 1 warning (0.00 sec)

MariaDB [vk_local]> 
MariaDB [vk_local]> CREATE TABLE IF NOT EXISTS `vk_messages` (
    ->   `uid` int(11) unsigned NOT NULL AUTO_INCREMENT,
    ->   `msg_id` int(11) NOT NULL,
    ->   `msg_chat` int(11) NOT NULL,
    ->   `msg_dialog` int(11) NOT NULL,
    ->   `msg_user` int(11) NOT NULL,
    ->   `msg_date` int(11) unsigned NOT NULL,
    ->   `msg_body` text CHARACTER SET utf8mb4 NOT NULL,
    ->   `msg_attach` tinyint(1) NOT NULL,
    ->   `msg_forwarded` tinyint(1) NOT NULL,
    ->   PRIMARY KEY (`uid`),
    ->   UNIQUE KEY `msg_uid` (`msg_id`,`msg_chat`,`msg_dialog`),
    ->   KEY `user` (`msg_user`),
    ->   KEY `attach` (`msg_attach`),
    ->   KEY `forwarded` (`msg_forwarded`)
    -> ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
Query OK, 0 rows affected, 1 warning (0.00 sec)

MariaDB [vk_local]> 
MariaDB [vk_local]> CREATE TABLE IF NOT EXISTS `vk_messages_attach` (
    ->   `uid` int(11) NOT NULL AUTO_INCREMENT,
    ->   `wall_id` int(11) NOT NULL,
    ->   `type` varchar(255) NOT NULL,
    ->   `is_local` tinyint(1) NOT NULL,
    ->   `attach_id` int(11) NOT NULL,
    ->   `owner_id` int(11) NOT NULL,
    ->   `uri` text NOT NULL,
    ->   `path` varchar(255) NOT NULL,
    ->   `width` smallint(5) unsigned NOT NULL,
    ->   `height` smallint(5) unsigned NOT NULL,
    ->   `text` text NOT NULL,
    ->   `date` int(11) NOT NULL,
    ->   `access_key` varchar(255) NOT NULL,
    ->   `title` text NOT NULL,
    ->   `duration` int(11) NOT NULL,
    ->   `player` text NOT NULL,
    ->   `link_url` text NOT NULL,
    ->   `caption` varchar(255) NOT NULL,
    ->   PRIMARY KEY (`uid`),
    ->   UNIQUE KEY `uniqid` (`wall_id`,`attach_id`),
    ->   KEY `local` (`is_local`),
    ->   KEY `width` (`width`),
    ->   KEY `height` (`height`)
    -> ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
Query OK, 0 rows affected, 1 warning (0.00 sec)

MariaDB [vk_local]> 
MariaDB [vk_local]> CREATE TABLE IF NOT EXISTS `vk_stickers` (
    ->   `product` int(11) NOT NULL,
    ->   `sticker` int(11) NOT NULL,
    ->   `width` int(10) unsigned NOT NULL,
    ->   `height` int(10) unsigned NOT NULL,
    ->   `uri` varchar(255) NOT NULL,
    ->   `path` varchar(255) NOT NULL,
    ->   `in_queue` tinyint(4) NOT NULL,
    ->   UNIQUE KEY `stick` (`product`,`sticker`),
    ->   KEY `product` (`product`),
    ->   KEY `queue` (`in_queue`)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Query OK, 0 rows affected, 1 warning (0.00 sec)

MariaDB [vk_local]> 
MariaDB [vk_local]> UPDATE `vk_status` SET `val` = '2018050201' WHERE `key` = 'version';
Query OK, 1 row affected (0.10 sec)
Rows matched: 1  Changed: 1  Warnings: 0

**Comment by VetalRacer** [comment]
ошибка пропала, теперь просто пустая страница с шапкой сверху... я явно что-то делаю не так...

**Comment by Chiaki** [comment]
Судя по первым сообщениям об ошибке, некоторые поля у вас уже были в базе что довольно странно если вы обновлялись с 0.7.7 до 0.8.0.

Для лучшего понимания ситуации опишите пожалуйста после каких действий у вас появилось сообщение "Структура базы данных устарела.".

Если отображается просто пустая страница, то вероятно у вас отключен вывод ошибок PHP, а с базой данных у вас сейчас какая-то проблема. Я рекомендую сравнить структуру БД из vkbk.sql с вашей базой.

**Comment by VetalRacer** [comment]
Ставил с нуля, по порядку:
1) поставил apach2
2) поставил бд
3) поставил php7.0
4) создал базу данных и mysql -uroot -p "БД" < /.../VKBK/vkbk.sql
5) настроил cfg,php
6) помучился с php7.0 (нужно было доставить php7.0-mysqlnd),# phpenmod mysqlnd 
и теперь выдавал ошибку описанную выше...

конфиг apache2:

[sudo] пароль для vracer: 
<VirtualHost *:80>
    ServerName vk.local
    ServerAdmin mail@vk.local
    ServerAlias www.vk.local
    DocumentRoot /var/www/vk.local
    CustomLog ${APACHE_LOG_DIR}/vk.local.access.log combined
    ErrorLog ${APACHE_LOG_DIR}/vk.local.error.log
    <Directory /var/www/vk.local>
        Options +Includes +Indexes +ExecCGI
        AllowOverride All
    </Directory>
</VirtualHost>

**Comment by Chiaki** [comment]
Причина появления сообщения: версия БД скрипта не была обновлена для 0.8.0 в файле vkbk.sql - **исправлено**.

Если вы ещё не производили синхронизацию, то можно убить базу и импортировать из vkbk.sql после чего выполнить запрос: 
`UPDATE `vk_status` SET `val` = '2018050201' WHERE `key` = 'version';`
После этого сообщение об устаревшей структуре БД должно исчезнуть.

**Comment by VetalRacer** [comment]
помогло! только ( UPDATE `vk_status` SET `val` = '2018050201' WHERE `key` = 'version'; )
Но увы все так же шапка и пустая белая область, ощущение что к vk прилодению не коннектится по каким-то причинам (в статистике вк приложения 0 использований api)

**Comment by Chiaki** [comment]
Ок. Давайте разбираться дальше.
На главной странице VKBK есть форма авторизации, либо исключительно белая область?
Проверьте есть ли ошибки в ErrorLog'е. Можно добавить в cfg.php error_reporting(E_ALL);
Для 0.8.0 согласно [инструкции](https://github.com/Chiaki/VKBK/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0) вы создавали Standalone приложение?

**Comment by VetalRacer** [comment]
на главной пусто, только шапка и все...
вот ошибки лога

[Sat Aug 18 23:40:15.857028 2018] [:error] [pid 640] [client 192.168.1.244:57650] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/vk.local/classes/VK/VK.php:65\nStack trace:\n#0 /var/www/vk.local/index.php(64): VK->__construct(ИД, 'КЛЮЧ...')\n#1 {main}\n  thrown in /var/www/vk.local/classes/VK/VK.php on line 65

ИД и КЛЮЧ поменял тут)

**Comment by Chiaki** [comment]
Судя по ошибке проблема с CURL. Похоже он у вас не подключен\разрешен. Для линукса если не ошибаюсь это php7.0-curl но название пакета может отличаться в зависимости от дистрибутива.

**Comment by loginith** [comment]
К слову, в таблице vk_messages_attach требуется исправить структуру, поля caption, text, и title должны быть utf8mb4.

**Comment by Chiaki** [comment]
По-хорошему надо большую часть текстовых полей уже переводить в utf8mb4, так как в начале данного типа кодировки не было совсем. Но думаю это уже когда рефакторингом буду заниматься.
